# Generated by Django 6.0.3 on 2026-04-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nombre_medida', models.CharField(max_length=20)),
                ('nombre_unidad', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('minimo', models.FloatField()),
                ('maximo', models.FloatField()),
            ],
        ),
    ]
