# Generated by Django 6.0.3 on 2026-04-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0002_regla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.IntegerField()),
            ],
        ),
    ]
