# Generated by Django 6.0.3 on 2026-04-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0003_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='usuario',
        ),
    ]
