# Generated by Django 6.0.2 on 2026-04-08 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0007_remove_usuario_user_usuario_password_usuario_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidades',
            name='max',
        ),
        migrations.RemoveField(
            model_name='unidades',
            name='min',
        ),
        migrations.RemoveField(
            model_name='unidades',
            name='step',
        ),
        migrations.CreateModel(
            name='MedidasUnidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maximo', models.FloatField()),
                ('minimo', models.FloatField()),
                ('step', models.FloatField()),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estandar.medidas')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estandar.unidades')),
            ],
        ),
    ]
