# Generated by Django 6.0.2 on 2026-04-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0008_remove_unidades_max_remove_unidades_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('estandard', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='proyectos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='unidades',
        ),
    ]
