# Generated by Django 6.0.2 on 2026-05-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0009_proyecto_delete_usuario_remove_medidas_unidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('reglas', models.ManyToManyField(to='estandar.regla')),
            ],
        ),
    ]
