# Generated by Django 6.0.3 on 2026-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0010_estandar'),
    ]

    operations = [
        migrations.AddField(
            model_name='estandar',
            name='orden',
            field=models.JSONField(default=list),
        ),
    ]
