# Generated by Django 6.0.3 on 2026-06-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0011_estandar_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='estandar',
            name='UMBRAL_CUIDADO',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='estandar',
            name='UMBRAL_PELIGRO',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='estandar',
            name='UMBRAL_URGENTE',
            field=models.IntegerField(default=3),
        ),
    ]
