# Generated by Django 6.0.3 on 2026-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0012_estandar_umbral_cuidado_estandar_umbral_peligro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('estandard', models.CharField(max_length=20)),
                ('csv_temporal', models.TextField()),
                ('transformaciones_pendientes', models.JSONField(default=list)),
            ],
        ),
    ]
