# Generated by Django 6.0.3 on 2026-06-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0013_proyectotemporal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProyectoTemporal',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='columnas_excluidas',
            field=models.JSONField(default=list),
        ),
    ]
