# Generated by Django 6.0.3 on 2026-06-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0014_delete_proyectotemporal_proyecto_columnas_excluidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='filas_confirmadas',
            field=models.JSONField(default=list),
        ),
    ]
