# Generated by Django 6.0.3 on 2026-06-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0015_proyecto_filas_confirmadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='regla',
            name='departamento',
            field=models.CharField(default='General', max_length=20),
        ),
    ]
