# Generated by Django 6.0.3 on 2026-06-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0016_regla_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estandar',
            name='departamento',
            field=models.CharField(default='General', max_length=20),
        ),
    ]
